### ISSUE TITLE
Test Data to complete journey

### ISSUE THREAD

**Issue by tomwoodcock1981** [neilstudd/technical-tests#6]
Good evening,

Do you have a test account number and sort code that can be used?

Or, is it sufficient for this test to complete this form without submitting and assert against the validation prompts for the account details?

Thank you in advance.

Tom

**Comment by neilstudd** [comment]
Hi Tom,

For the purposes of this exercise, it's only necessary to proceed as far as the page which lists all of the different prices (the YourResults page). You don't need to go through the switching process - I'll update the instructions to make things clearer.

Do let us know if you have any further questions!

Thanks,
Neil

**Comment by tomwoodcock1981** [comment]
Neil,

Brilliant, thanks for the swift reply and sorry to interrupt your evening!

Thanks,

Tom
