### ISSUE TITLE
Clarification on 3 test limit, Test coverage and Assertion

### ISSUE THREAD

**Issue by asifAutomationRepo** [neilstudd/technical-tests#7]
Hello there,

Thanks for inviting me to take the technical test. Can I have clarification on following please?
Sorry for my long winded questions. I think answers for them will be short :)

**Q1: 3 test limit:** 
I have noticed a question answered regarding 3 tests that we are looking for 3 scenarios in total. Can I use bdd examples  to ensure multiple combinations and permutation in the user journey is covered? Because unit test runner interprets each example row as separate tests (which they are).
Readability will effect slightly for this but I guess I can justify my reason in the interview.

**Q2: Test coverage:** 
Does all the combination and permutation need to be covered? Or pre-selected options are fine for this test (because as mentioned in introduction: the user journeys must always be functional and we need to ensure that they are working on every check in of the code.)

For example: 
1. Following options in your supplier section: 
a. Do you have your bill handy? (2 possible outcome)
b. What do you want to compare? (3 possible outcome)
c. Is your gas & electricity from the same supplier?
d. Who supplies your energy? (Related providers output based on first 3 options)

2. Your energy section:
a. Same question (combination and permutation including gas and electricity) 
b. Combination of “I don’t have my bill” (in your supplier section) and “I don't know” (How much do you currently spend on electricity) will open /energy/v2/yourUsage?AFFCLIE=TST page

3. Your details section:
Same question (combination and permutation or for this one I can include all tariffs and all payment types)

**Q3: Assertion:** 
Are we looking for specific value for assertion in results page? (such as how many available tariffs for that search criteria, if their price displayed accordingly). I'm guessing energy provider result value can be tested by Data-driven testing (such as testing api endpoint response) and is out of scope for our tests. Therefore intent of these tests is to make sure results are displayed relevant to my selected search criteria/filter (strictly user journey). Please correct me if my assumption is wrong.

Thanks in advance :)
Asif

**Comment by neilstudd** [comment]
Hi Asif,

Thanks for your questions! I will try to answer them as briefly as I can :)

**Q1: 3 test limit**
You're correct that this is open to interpretation, and you definitely score points for asking! We're certainly looking for creativity, and to be able to test as much (which is valuable) as possible within some definition of "three tests". For the purposes of this exercise, we'll allow one scenario with an examples table to count as just 1 test.

**Q2: Test coverage**
This follows on from above really. Again, it's great that you've started to enumerate all of the possible selections. See what you can cover within three tests: we'll certainly ask you to justify what you tested (and didn't test) within the constraints available.

**Q3: Assertion**
A simple assertion on the results page (something that validates you're on the price page) will suffice. There are complexities to deal with on the price page (e.g. particular providers may or may not appear, depending on factors which are outside are control, and provider response times can vary up to 30 seconds too). We would certainly test requests/responses to individual providers through alternate means, which is outside the scope of this exercise.

Thanks and good luck! If you have any more questions, please ask away.

**Comment by asifAutomationRepo** [comment]
Many thanks for your answers Neil. 
Issue closed :)
